apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-elasticsearch
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/sidhuni/tools-app.git'  # your repo
    targetRevision: main
    path: sre-tools       # folder containing the actual CR manifests
    directory:
      recurse: true       # recursively include subfolders if needed

  destination:
    server: "https://kubernetes.default.svc"
    namespace: eck-elasticsearch   # namespace where Elasticsearch will live

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/resourceVersion
        - /metadata/managedFields
        - /data
