apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 22.1.6   
    chart: elasticsearch
    helm:
      valueFiles:
      - $values/elasticsearch/values.yaml
  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: elasticsearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
