apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/sidhuni/apps-repo.git
    targetRevision: main
    ref: values
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.4.2   # choose the version you want
    helm:
      valueFiles:
      - $values/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
    syncOptions:
    - Validate=false
