apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kafka-cluster
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 32.4.3
    chart: kafka
    helm:
      valueFiles:
      - $values/kafka/values.yaml
  - repoURL: https://github.com/sidhuni/tools-app.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - Validate=false
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    # Service NodePort (Already done)
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/ports/0/nodePort

    # PVC Metadata & Resources (Already done)
    - group: ""
      kind: PersistentVolumeClaim
      jqPathExpressions:
        - .metadata.creationTimestamp
        - .metadata.uid
        - .metadata.resourceVersion
        - .metadata.managedFields
        - .spec.resources

    # StatefulSet template metadata (Already done, but extending to checksums)
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.metadata

    # StatefulSet Metadata (Already done)
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/resourceVersion
        - /metadata/managedFields

    # Secret Metadata (Already done)
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/creationTimestamp
        - /metadata/uid
        - /metadata/resourceVersion
        - /metadata/managedFields
        
    # --- NEW RULES TO FIX DRIFT ---

    # 1. Ignore Secret Data (fixes the Kraft ID drift)
    - group: ""
      kind: Secret
      jsonPointers:
        - /data

    # 2. Ignore Checksum Annotations in StatefulSet template (fixes the checksum drift)
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1configuration
        - /spec/template/metadata/annotations/checksum~1jmx-configuration
        - /spec/template/metadata/annotations/checksum~1secret