apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-local-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" # Running every minute for your test
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:16
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgres-password
            volumeMounts:
            - name: backup-dir
              mountPath: /backups
            command:
              command:
              - /bin/sh
              - -c
              - |
                set -e
                DATE_FOLDER=$(date +%Y-%m-%d)
                TARGET_DIR="/backups/$DATE_FOLDER"
                mkdir -p "$TARGET_DIR"

                echo "--- Starting Local Backup: $DATE_FOLDER ---"
                
                # Use 'postgres' as the host if that is your service name
                HOST="postgresql" 
                USER="postgres"

                # 1. Test Connection first
                if ! psql -h $HOST -U $USER -c "SELECT 1" > /dev/null 2>&1; then
                  echo "ERROR: Cannot connect to $HOST. Check password or service name."
                  exit 1
                fi

                # 2. Get DB list (finds Grafana, Temporal, etc.)
                DB_LIST=$(psql -h $HOST -U $USER -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB..."
                  if pg_dump -h $HOST -U $USER "$DB" > "$TARGET_DIR/$DB.sql"; then
                    echo "  [SUCCESS] $DB"
                  else
                    echo "  [FAILED] $DB"
                  fi
                done

                # 3. Prevent immediate exit (Optional for debugging)
                echo "Backup cycle complete. Files in $TARGET_DIR:"
                ls -lh "$TARGET_DIR"
          volumes:
          - name: backup-dir
            persistentVolumeClaim:
              claimName: postgres-local-backups
