apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-s3-backup
  namespace: postgresql
spec:
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: postgresql
          securityContext:
            fsGroup: 1001
          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
                - name: BUCKET
                  value: "postgresqlb-backup"
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  # Install AWS CLI to writable directory
                  echo "Installing AWS CLI..."
                  cd /tmp
                  curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
                  python3 -c "import zipfile; zipfile.ZipFile('awscliv2.zip').extractall()"
                  ./aws/install -i /tmp/aws-cli -b /tmp/bin > /dev/null
                  export PATH=$PATH:/tmp/bin

                  TIMESTAMP=$(date +%Y-%m-%d)
                  echo "--- Starting S3 Backup for $TIMESTAMP ---"

                  DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At \
                    -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  for DB in $DB_LIST; do
                    echo "Backing up: $DB"

                    pg_dump -h postgresql -U "$PGUSER" "$DB" | gzip > "/tmp/${DB}.sql.gz"

                    aws s3 cp "/tmp/${DB}.sql.gz" \
                      "s3://${BUCKET}/${TIMESTAMP}/${DB}.sql.gz"

                    echo "Uploaded $DB.sql.gz to S3"
                  done

                  echo "--- All backups finished successfully ---"
          restartPolicy: OnFailure
