apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: postgres:16
            envFrom:
              - secretRef:
                  name: postgres-backup-creds
            volumeMounts:
              - name: backup-storage
                mountPath: /backups
            command:
              - /bin/sh
              - -c
              - |
                set -e

                echo "Automatic Backup Started at $(date -u)"

                DATE=$(date +%Y-%m-%d)
                BACKUP_DIR="/backups/$DATE"
                mkdir -p "$BACKUP_DIR"

                echo "Testing connection..."
                psql -h postgresql -c "SELECT 1;" >/dev/null

                DB_LIST=$(psql -h postgresql -At \
                  -c "SELECT datname FROM pg_database WHERE datistemplate = false;")

                for DB in $DB_LIST; do
                  echo "Backing up $DB"
                  pg_dump -h postgresql "$DB" | gzip > "$BACKUP_DIR/$DB.sql.gz"
                done

                echo "Cleaning old backups..."
                cd /backups && ls -dt */ | tail -n +6 | xargs -r rm -rf

                echo "✅ Backup completed"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
