apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *"  # Once a minute for testing
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # This ensures the pod can write to the PVC on Rancher Desktop
          securityContext:
            fsGroup: 1001
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
              - /bin/sh
              - -c
              - |
                set -e
                
                # 1. Install AWS CLI to /tmp (writable by user 1001)
                echo "Installing AWS CLI..."
                cd /tmp
                curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

                # Use Python to extract because 'unzip' 
                echo "Extracting AWS CLI using Python..."
                python3 -c "import zipfile; import sys; zipfile.ZipFile('awscliv2.zip').extractall()"
                
                echo "Installing..."
                ./aws/install -i /tmp/aws-cli -b /tmp/bin > /dev/null
                export PATH=$PATH:/tmp/bin

                # 2. Set current date for folder name
                TIMESTAMP=$(date +%Y-%m-%d)
                echo "--- Starting S3 Backup for $TIMESTAMP ---"

                # 3. List all databases
                DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                # 4. Backup and Stream to S3
                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  echo " Uploaded $DB.sql.gz to S3"
                done
                
                echo "--- All backups finished successfully ---"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
