apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:16
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgres-password
            # We add the volume so the folders don't disappear when the pod finishes
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            command:
              - /bin/sh
              - -c
              - |
                echo "Automatic Backup Started at $(date)"
                
                # 1. Create a folder for Today
                DATE_FOLDER=$(date +%Y-%m-%d)
                mkdir -p /backups/$DATE_FOLDER
                
                # 2. Get list of ALL databases (finds Grafana, Temporal, etc.)
                # We connect to 'postgres' DB just to get the list of names
                DB_LIST=$(psql -h postgresql -U postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")
                
                for DB in $DB_LIST; do
                  echo "Backing up Database: $DB"
                  # 3. Save to the dated folder
                  pg_dump -h postgresql -U postgres "$DB" > "/backups/$DATE_FOLDER/$DB.sql"
                  echo "Done: $DB. Size: $(du -sh /backups/$DATE_FOLDER/$DB.sql | cut -f1)"
                done
                
                # 4. Cleanup: Only keep last 5 days of folders
                cd /backups && ls -dt */ | tail -n +6 | xargs -I {} rm -rf "{}"
                
                echo "All Backups Completed Successfully."
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-local-backups
