apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              # Use the exact cached image from your running pod
              image: registry-1.docker.io/bitnami/postgresql:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets
                      key: user_password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  DATE=$(date +%Y-%m-%d_%H-%M)
                  BACKUP_DIR="/backups/$DATE"
                  mkdir -p "$BACKUP_DIR"

                  echo "--- Backup Started: $(date) ---"
                  
                  # Connect to 'postgres' to get the list of other databases
                  DB_LIST=$(psql -h postgresql -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                  for DB in $DB_LIST; do
                    FILE_PATH="$BACKUP_DIR/$DB.sql.gz"
                    echo "Backing up database: $DB ..."
                    
                    pg_dump -h postgresql -U "$PGUSER" "$DB" | gzip > "$FILE_PATH"
                    
                    # --- NEW: Get and print the file size ---
                    SIZE=$(du -sh "$FILE_PATH" | cut -f1)
                    echo "✅ Done: $DB.sql.gz (Size: $SIZE)"
                  done

                  echo "Cleaning up backups older than 5 days..."
                  find /backups -type d -mtime +5 -exec rm -rf {} +
                  
                  echo "--- All backups finished successfully ---"
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
