apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-local-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:16
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgres-password
            volumeMounts:
            - name: backup-dir
              mountPath: /backups
            command:
              - /bin/sh
              - -c
              - |
                set -e
                DATE_FOLDER=$(date +%Y-%m-%d)
                TARGET_DIR="/backups/$DATE_FOLDER"
                mkdir -p "$TARGET_DIR"
                
                # Dynamic discovery of all DBs (Grafana, Temporal, etc.)
                DB_LIST=$(psql -h postgresql -U postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")
                
                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  pg_dump -h postgresql -U postgres "$DB" > "$TARGET_DIR/$DB.sql"
                done
                
                # Keep last 5 days
                cd /backups && ls -dt */ | tail -n +6 | xargs -I {} rm -rf "{}"
          # 🔥 THIS LINE MUST BE AT THIS INDENTATION LEVEL (under spec.jobTemplate.spec.template.spec)
          restartPolicy: OnFailure
          volumes:
          - name: backup-dir
            persistentVolumeClaim:
              claimName: postgres-local-backups
