apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "0 2 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/postgresql:16
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: postgres-password
            command:
              - /bin/sh
              - -c
              - |
                # Use /tmp for local testing so we don't touch the DB disk
                FILENAME="/tmp/backup-$(date +%F).sql"
                echo "Starting backup to $FILENAME..."
                pg_dump -h postgresql -U admin chms > $FILENAME
                echo "Backup size: $(du -sh $FILENAME)"
                # Local cleanup logic (keeps last 5 files in /tmp)
                ls -1t /tmp/backup-*.sql | tail -n +6 | xargs -r rm
                echo "Cleanup complete."
          restartPolicy: OnFailure
          # No volumes needed for a simple local test to /tmp
