apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          restartPolicy: OnFailure

          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-local-backups
            - name: aws-tools 
              emptyDir: {}

          initContainers:
          - name: install-aws
            image: amazon/aws-cli:latest
            command: ["/bin/sh", "-c", "cp -pr /usr/local/aws-cli /target/"]
            volumeMounts:
            - name: aws-tools
              mountPath: /target

          containers:
            - name: backup
              image: registry-1.docker.io/bitnami/postgresql:latest
              securityContext:
                runAsUser: 1001
              env:
                - name: PGUSER
                  value: "admin"
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secrets # Uses your existing Opaque secret
                      key: user_password
                - name: BUCKET
                  value: "postgresqlb-backup"
                - name: PGHOST
                  value: "postgresql"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
                - name: aws-tools
                  mountPath: /opt/aws-tools
              command:
              - /bin/sh
              - -c
              - |
                set -e
                
                # 1. Point to the SPECIFIC version folder we saw in your logs
                # We also add the 'dist' folder where the actual binary lives
                export AWS_HOME=/opt/aws-tools/aws-cli/v2/2.33.20
                export PATH=$PATH:$AWS_HOME/dist:$AWS_HOME/bin
                
                echo "--- Tools Check ---"
                # Call the binary by its full path to be 100% sure
                /opt/aws-tools/aws-cli/v2/2.33.20/dist/aws --version
                
                # Now set the alias so the rest of your script works
                alias aws='/opt/aws-tools/aws-cli/v2/2.33.20/dist/aws'

                TIMESTAMP=$(date +%Y-%m-%d)
                echo "--- Starting Backup for $TIMESTAMP ---"

                # DB Logic
                DB_LIST=$(psql -h $PGHOST -U "$PGUSER" -d postgres -At -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';")

                for DB in $DB_LIST; do
                  echo "Backing up: $DB"
                  # Use the full path for the aws command to prevent "command not found"
                  pg_dump -h $PGHOST -U "$PGUSER" "$DB" | gzip | /opt/aws-tools/aws-cli/v2/2.33.20/dist/aws s3 cp - s3://$BUCKET/$TIMESTAMP/$DB.sql.gz
                  echo "✅ Uploaded $DB.sql.gz"
                done
