apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: postgresql
spec:
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:16
            imagePullPolicy: IfNotPresent
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgres-password
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            command:
              - /bin/sh
              - -c
              - |
                set -e
                BACKUP_DIR="/backups"
                TIMESTAMP=$(date +%Y%m%d%H%M)
                FILE_NAME="$BACKUP_DIR/backup-$TIMESTAMP.sql"

                echo "Starting Backup: $FILE_NAME"
                pg_dump -h postgresql -U postgres chms > "$FILE_NAME"
                
                echo "Backup Complete. Rotating old files..."
                # Keep only the 5 most recent .sql files
                cd $BACKUP_DIR
                ls -tp *.sql | grep -v '/$' | tail -n +6 | xargs -I {} rm -- {}
                
                echo "Current backups in storage:"
                ls -lh $BACKUP_DIR
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgresql-backup-pvc # Make sure this PVC exists!