apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://mycharts       # ChartMuseum repo name (from helm repo add)
    chart: common-app-chart
    targetRevision: 0.1.0

    helm:
      valueFiles:
        - $valuesrepo/app1/values.yaml

  sources:
    - repoURL: https://github.com/sidhuni/my-checksum-helmchart.git
      targetRevision: main
      ref: valuesrepo

  destination:
    server: https://kubernetes.default.svc
    namespace: app1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
